Onotole branch
ClevertecFrontendLab/sprint1-onotole-ololoev pull request #1
Opened 2023-01-30 18:42 UTC by onotole-ololoev

2023-01-30 18:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675104320/content-window.png)

2023-01-30 18:47 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215567541-386ef211-9f08-4fc9-aaa6-31029ae9720b.png)
не соответствует макету

2023-01-30 18:49 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215567833-a23fb315-c083-460a-b8bc-7c50cda8f8ce.png)
выделяться цветом только активные разделы

2023-01-31 06:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675148061/content-window.png)

2023-01-31 07:20 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215691105-ba862350-1380-4fe4-97dc-ab1180b22245.png)
карточки не по макету, в мобильной версии перекрывается контент,  если вы делаете через один компонент  то удобно через grid  т.к  он способен менять структуру, но если не получается один можете через несколько компонентов главное что б вы успели сделать

2023-01-31 13:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/onotole-ololoev/1675170207/content-window.png)

2023-01-31 14:50 UTC, SergeyGlazun approved these changes

2023-01-31 14:50 UTC, merged